config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genero.rb
class Genero < ApplicationRecord

  has_many :usuarios

end

app/models/usuario.rb
class Usuario < ApplicationRecord

  belongs_to :genero

  validates :nome, :idade, :genero_id, :cpf, presence:true
  validates :cpf, uniqueness:true
s
  validates_length_of :cpf, is: 14 
  validates_numericality_of :idade, minimum: 18, maximum: 115


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def index
      @usuarios = Usuario.all
  end

  def show
      @usuario = Usuario.find(params[:id])
  end

  def edit
      @usuario = Usuario.find(params[:id])
  end

  def update
      @usuario = Usuario.find(params[:id])
      usuario_params = params.require(:usuario).permit!
      if @usuario.update(usuario_params)
          redirect_to @usuario
      else
          render :edit
      end
  end

  def new
      @usuario = Usuario.new
  end

  def create
      usuario_params = params.require(:usuario).permit!
      @usuario = Usuario.new(params[:usuario])
      if @usuario.save
          redirect_to @usuario
      else
          render :new
      end
  end
  
  def destroy
      @usuario = Usuario.find(params[:id])
      @usuario.destroy
      redirect_to usuarios_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/usuari_os_helper.rb
module UsuariOsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark" style="background-color: #7a297a">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Total IP</a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Total IP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-dark" style="background-color: #7a297a">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Total IP</a>
    <a class="nav-item nav-link" ><%= link_to 'Cadastrar Novo usuário', new_usuario_path %></a>
  </div>
  </nav>


  <%= yield %>
  </body>
</html>

app/views/usuarios/edit.html.erb
<br> 
<br>
<%=form_for(@usuario) do |f| %>

<% if @usuario.errors.any? %>
	<div class="alert alert-danger">
		<ul>
			<% @usuario.errors.full_messages.each do |mensagem| %>
				<li><%= mensagem %></li>
			<% end %>
		</ul>
	</div>
<% end %>

	<form class="form-horizontal">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Editar dados do usuário</h3>
		</div>
		<br> 
	</div>

	<div class="panel-body">
		<div class="form-group">
			<label for="#" class="col-sm-2 control-label"><%= f.label :Nome %></label>
			<div class="col-sm-4">
			<%= f.text_field :nome, class:"form-control" %>
			</div>
	</div>

	<div class="form-group">
		<label class="col-sm-2 control-label"><%= f.label :Idade %></label>
		<div class="col-sm-2">
		<%= f.number_field :idade, class:"form-control" %>
		</div>
	</div>

<div class="form-group">
		<label class="col-sm-2 control-label"><%= f.label :CPF %></label>
<div class="col-sm-2">
<%= f.text_field :cpf, 'data-mask': '000.000.000-00', class:"form-control" %>
</div>
</div>

            <div class="form-group">
                <label class="col-sm-2 control-label"><%= f.label :Gênero %></label>
                <div class="col-sm-2">
                    <%= f.collection_select :genero_id, Genero.all, :id, :opcoesg, class:"form-control" %>  
                </div>
            </div>

			
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-primary">Salvar</button>
					<button type="button" class="btn btn-warning"><%= link_to "Voltar", usuarios_path%></button>

				</div>

			</div>
		</div>

	</form>
    <%end%>

app/views/usuarios/index.html.erb
 <br> 
 <br> 
<table class="table">
<thead class="thead-dark">

  <tr>
    <th scope="col">Status</th>
    <th scope="col">Nome</th>
    <th scope="col">Idade</th>
    <th scope="col">Gênero</th>
    <th scope="col">CPF</th>
  </tr>
</thead>
<tbody>
    <% @usuarios.each do |usuario| %>
    <tr>
        <th scope="row">Ativo</th>
        <td><%= link_to usuario.nome, usuario %></td>
        <td><%= usuario.idade %></td>
        <td><%= usuario.genero.opcoesg %></td>
        <td><%= usuario.cpf %></td>
    </tr>
  <%end%>
  </tbody>
</table>

app/views/usuarios/new.html.erb
<br> 
<br>
<%=form_for(@usuario) do |f| %>
  <form class="form-horizontal">
  <div class="panel panel-default">
      <div class="panel-heading">
          <h3 class="panel-title">Cadastrar Novo Usuário</h3>
      </div>
  </div>
  <br> 

  <div class="panel-body">
      <div class="form-group">
          <label for="#" class="col-sm-2 control-label"><%= f.label :Nome %></label>
          
          <div class="col-sm-4">
              <%= f.text_field :nome, class:"form-control" %>
          </div>
      </div>

      <div class="form-group">
          <label class="col-sm-2 control-label"><%= f.label :Idade %></label>
          <div class="col-sm-2">
              <%= f.number_field :idade, class:"form-control" %>
          </div>
      </div>

      <div class="form-group">
          <label class="col-sm-2 control-label"><%= f.label :CPF %></label>
          <div class="col-sm-2">
              <%= f.text_field:cpf, 'data-mask': '000.000.000-00', class:"form-control" %>
          </div>
      </div>

      <div class="form-group">
          <label class="col-sm-2 control-label"><%= f.label :Gênero %></label>
          <div class="col-sm-2">
              <%= f.collection_select :genero_id, Genero.all, :id, :opcoesg, class:"form-control" %>  
          </div>
      </div>

      
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">Salvar</button>
              <button type="button" class="btn btn-warning"><%= link_to "Voltar", usuarios_path%></button>
          </div>

      </div>
  </div>

</form>
<%end%>

app/views/usuarios/show.html.erb
<br> 
<br>

<ul class="list-group">

<a href="#" class="list-group-item list-group-item-dark">Usuário Selecionado</a>

  <li class="list-group-item list-group-item-action"><span class="badge badge-primary badge-pill">NOME</span>  <%= @usuario.nome%></li>
  <li class="list-group-item list-group-item-action"><span class="badge badge-primary badge-pill">IDADE</span> <%= @usuario.idade%></li>
  <li class="list-group-item list-group-item-action"><span class="badge badge-primary badge-pill">GÊNERO</span> <%= @usuario.genero.opcoesg%> </li>
  <li class="list-group-item list-group-item-action"><span class="badge badge-primary badge-pill">CPF</span> <%=@usuario.cpf%></li>

</ul>
<br> 
<br>


<button type="button" class="btn btn-success"><%= link_to "Usuários", usuarios_path%></button>
<button type="button" class="btn btn-warning"><%= link_to "Editar dados", edit_usuario_path(@usuario)%></button>
<button type="button" class="btn btn-danger"><%= link_to "Deletar usuário", usuario_path(@usuario), method: :delete, data:{confirm: "Deseja deletar esta receita?"} %></button>